#!/usr/bin/env node
var path = require('path');
var fs = require('fs');

var mishnah = require('../index');
var moment = require('moment');
var H = require('hebcal');

var day = new moment([2017, 8, 10]);
var output = '';
for (var i = 0; i < 420; i++) {
  output += mishnah.prettyFormat(mishnah.getToday(day), true);
  output +=
    i % 7 === 6
      ? ',' + H.HDate(day.toDate()).getSedra('h').join(' - ') + '\n'
      : ',';
  day.add(1, 'd');
}

fs.writeFileSync(path.join(__dirname, '..', 'data', 'calendar.csv'), output, 'utf-8');
