#!/usr/bin/env node
var path = require("path");
var fs = require("fs");
var hebcal = require("hebcal");

var mishnah = require("../index");
var moment = require("moment");

var day = new moment();
day.add(7- day.day(), 'd');
var output='<html><head><meta charset="utf-8"></head><body><table><tr>';
for(var i = 0; i < 7; i++) {
  output += '<td><br/>' + day.format("D MMMM")+"<br/>" +
    new hebcal.HDate(day.toDate()).toString('h').split(" ").slice(0,2).join(" ")+ "<br/><br/>"+
   mishnah.getToday(day, true) + "<br/>&nbsp;";
  day.add(1,"d");
}
output+="</tr></table></body></html>";
console.log(output);
fs.writeFileSync(path.join(__dirname, "..","data","week.html"), output);

